config/routes.rb
Rails.application.routes.draw do
  resources :tabulae14s
  rutarel = ENV.fetch('RUTA_RELATIVA', 'heb412/')
  scope rutarel do 

    devise_scope :usuario do
      get 'sign_out' => 'devise/sessions#destroy'

      # El siguiente para superar mala generación del action en el formulario
      # cuando se monta en sitio diferente a / y se autentica mal (genera 
      # /puntomontaje/puntomontaje/usuarios/sign_in )
      if (Rails.configuration.relative_url_root != '/') 
        ruta = File.join(Rails.configuration.relative_url_root, 
                         'usuarios/sign_in')
        post ruta, to: 'devise/sessions#create'
        get  ruta, to: 'devise/sessions#new'
      end
      get 'sign_up' => 'registrations#new', as: :sign_up
    end
    devise_for :usuarios, module: :devise,
      controllers: { registrations: "registrations" }
    as :usuario do
      get 'usuarios/edit' => 'devise/registrations#edit', 
        :as => 'editar_registro_usuario'    
      put 'usuarios/:id' => 'devise/registrations#update', 
        :as => 'registro_usuario'            
    end
    resources :usuarios, path_names: { new: 'nuevo', edit: 'edita' } 

    resources :elecciones, path_names: { new: 'nueva', edit: 'edita' } 

    get 'gracias' => 'sip/hogar#gracias', as: :gracias

    get 'ppd' => 'sip/hogar#ppd', as: :ppd 

    get '/tabulae14s/nuevomismopuesto/:tabulae14_id' =>
      'tabulae14s#nuevomismopuesto',
       as: :tabulae14_nuevomismopuesto

    get '/elecciones/:id/nacional' => 'elecciones#nacional',
      as: :elecciones_nacional
    get '/elecciones/:id/departamental/:coddep' => 'elecciones#departamental',
      as: :elecciones_departamental
    get '/elecciones/:id/municipal/:coddep/:codmun' => 'elecciones#municipal',
      as: :elecciones_municipal
    get '/elecciones/:id/zona/:coddep/:codmun/:zona' => 'elecciones#zona',
      as: :elecciones_zona
    get '/elecciones/:id/puesto/:coddep/:codmun/:zona/:puesto' => 
    'elecciones#puesto', as: :elecciones_puesto
    get '/elecciones/:id/mesa/:coddep/:codmun/:zona/:puesto/:mesa' => 
    'elecciones#mesa', as: :elecciones_mesa

    root 'sip/hogar#index'

    namespace :admin do
      ab = ::Ability.new
      ab.tablasbasicas.each do |t|
        if (t[0] == '') 
          c = t[1].pluralize
          resources c.to_sym, 
            path_names: { new: 'nueva', edit: 'edita' }
        end
      end
    end
  end

  mount Heb412Gen::Engine, at: rutarel, as: 'heb412_gen'
  mount Mr519Gen::Engine, at: rutarel, as: 'mr519_gen'
  mount Sip::Engine, at: rutarel, as: 'sip'
end

app/controllers/elecciones_controller.rb
class EleccionesController < ApplicationController
  before_action :set_eleccion, only: [
    :departamental, 
    :destroy,  
    :edit, 
    :mesa,
    :municipal,
    :nacional, 
    :puesto,
    :show, 
    :update,
    :zona
  ]

  def clase
    "::Eleccion"
  end

  def atributos_index
    [ 
      :id,
      :nombre,
      :numcandidatos,
      :geoelectoral_id,
      :fechaini_localizada,
      :fechafin_localizada
    ]
  end

  def atributos_show
    [ 
      :id,
      :nombre,
      :numcandidatos,
      :geoelectoral_id,
      :candidato1,
      :candidato2,
      :candidato3,
      :candidato4,
      :candidato5,
      :candidato6,
      :candidato7,
      :candidato8,
      :candidato9,
      :candidato10,
      :candidato11,
      :candidato12,
      :fechaini_localizada,
      :fechafin_localizada
    ]
  end

  def atributos_form
    atributos_show - [:id]
  end


  def vistas_manejadas
    ['Elecciones']
  end

  def nacional
    render layout: 'application'
  end

  def departamental
    poner_departamento

    render layout: 'application'
  end

  def municipal 
    poner_municipio

    render layout: 'application'
  end

  def zona 
    poner_zona

    render layout: 'application'
  end

  def puesto 
    poner_puesto

    render layout: 'application'
  end

  def mesa
    poner_mesa

    render layout: 'application'
  end


  private
    def set_eleccion
      @eleccion = @registro = Eleccion.find(params[:id])
    end

    def poner_departamento
      @departamento =  Sip::Departamento.
        where(id_pais: 170).
        where('sip_departamento.codreg=?', params[:coddep]).take!
    end

    def poner_municipio
      poner_departamento
      @municipio =  Sip::Municipio.
        where(id_departamento: @departamento.id).
        where('sip_municipio.codreg = ?', params[:codmun]).take!
    end

    def poner_zona
      poner_municipio
      @zona =  ::Zona.
        where(municipio_id: @municipio.id).
        where('zona.zona = ?', params[:zona]).take!
    end

    def poner_puesto
      poner_zona
      @puesto =  ::Puesto.
        where(zona_id: @zona.id).
        where('puesto.puesto = ?', params[:puesto]).take!
    end

    def poner_mesa
      poner_puesto
      @mesa =  ::Mesa.
        where(puesto_id: @puesto.id).
        where('mesa.mesa = ?', params[:mesa]).take!
    end


    def lista_params
      atributos_form
    end

    # Only allow a list of trusted parameters through.
    def eleccion_params
      params.require(:eleccion).permit(atributos_form)
    end
end

app/helpers/elecciones_helper.rb
module EleccionesHelper

  def promedio(campo, filtro)
    if filtro.include?(:municipio_id)
      s = Prome14.select("sum(#{campo})").where(filtro).to_sql 
    elsif filtro.include?(:departamento_id)
      s = Prome14.select("sum(#{campo})").
        joins('JOIN sip_municipio ON sip_municipio.id=prome14.municipio_id').
          where('sip_municipio.id_departamento=?', filtro[:departamento_id]).
          to_sql
    else  #Total nacional
      s = Prome14.select("sum(#{campo})").to_sql
    end

    p = Prome14.connection.execute(s)[0]['sum'].to_f
    pr = (p*100).to_i/100.0
    return pr.a_decimal_localizado
  end



  # De https://stats.stackexchange.com/questions/117741/adding-two-or-more-means-and-calculating-the-new-standard-deviation
  # se generaliza que cuando X_i son independientes E(sum X_i) = sum E(X_i)
  # y Var(sum X_i) = sum(Var(X_i))
  def desviacion(campo, filtro)
    if filtro.include?(:municipio_id)
      s = Desve14.select("sqrt(sum(#{campo}*#{campo}))").where(filtro).to_sql 
    elsif filtro.include?(:departamento_id)
      s = Desve14.select("sqrt(sum(#{campo}*#{campo}))").
        joins('JOIN sip_municipio ON sip_municipio.id=desve14.municipio_id').
          where('sip_municipio.id_departamento=?', filtro[:departamento_id]).
          to_sql
    else  #Total nacional
      s = Desve14.select("sqrt(sum(#{campo}*#{campo}))").to_sql
    end

    p = Desve14.connection.execute(s)[0]['sqrt'].to_f
    pr = (p*100).to_i/100.0
    return pr.a_decimal_localizado
  end


end

app/views/elecciones/_tabla_resultados.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Candidato</th>
      <th>Promedio</th>
      <th>Desviación Estándar</th>
    </tr>
  </thead>
  <tbody>
    <% (1..@eleccion.numcandidatos).each do |n| %>
      <tr>
        <td>
          <%= @eleccion['candidato' + n.to_s] %>:
        </td>
        <td align='right'>
          <%= promedio("c#{n}", @filtro) %>
        </td>
        <td align='right'>
          <%= desviacion("c#{n}", @filtro) %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td>
        Votos en Blanco
      </td>
      <td align='right'>
        <%= promedio("blanco", @filtro) %>
      </td>
      <td align='right'>
        <%= desviacion("blanco", @filtro) %>
      </td>
    </tr>
    <tr>
      <td>
        Votos no marcados
      </td>
      <td align='right'>
        <%= promedio("nomarcados", @filtro) %>
      </td>
      <td align='right'>
        <%= desviacion("nomarcados", @filtro) %>
      </td>
    </tr>
    <tr>
      <td>
        Votos nulos 
      </td>
      <td align='right'>
        <%= promedio("nulos", @filtro) %>
      </td>
      <td align='right'>
        <%= desviacion("nulos", @filtro) %>
      </td>
    </tr>
  </tbody>
</table>

app/views/elecciones/departamental.html.erb
<div class='row'>
  <div class='col-12' align='center'>
    Totales tabulados por departamento para <%= @eleccion.nombre %>
  </div>
</div>
<div class='row'>
  <div class='col-6' align='center'>
    Departamento: <%= @departamento.nombre %>
  </div>
</div>

<% @filtro = {
  departamento_id: @departamento.id 
} %>
<%= render partial: 'tabla_resultados' %>

<% Sip::Municipio.habilitados.where(id_departamento: @departamento.id).each do |m| %>
  <div class='ressubitem'>
    <%= link_to("Municipio #{m.nombre}", 
                elecciones_municipal_path(codmun: m.codreg)) %>
  </div>
<% end %>

<div class='ressuperitem'>
  <%= link_to('Total nacional', elecciones_nacional_path) %>
</div>

app/views/elecciones/mesa.html.erb
<div class='row'>
  <div class='col-12' align='center'>
    Totales tabulados por mesa para <%= @eleccion.nombre %>
  </div>
</div>
<div class='row'>
  <div class='col-6' align='center'>
    Departamento: <%= @departamento.nombre %>
  </div>
  <div class='col-6' align='center'>
    Municipio <%= @municipio.nombre %>
  </div>
</div>
<div class='row'>
  <div class='col-4' align='center'>
    Zona <%= @zona.zona %>
  </div>
  <div class='col-4' align='center'>
    Puesto <%= @puesto.puesto %>
  </div>
  <div class='col-4' align='center'>
    Mesa <%= @mesa.mesa %>
  </div>
</div>

<% @filtro = {
  mesa:@mesa.id,
  puesto: @puesto.id,
  zona: @zona.id,
  municipio_id: @municipio.id 
} %>
<%= render partial: 'tabla_resultados' %>

<div class='ressuperitem'>
  <%= link_to('Puesto de esta mesa', elecciones_puesto_path(
    puesto: @puesto.puesto)) %>
</div>

app/views/elecciones/municipal.html.erb
<div class='row'>
  <div class='col-12' align='center'>
    Totales tabulados por municipio para <%= @eleccion.nombre %>
  </div>
</div>
<div class='row'>
  <div class='col-6' align='center'>
    Departamento: <%= @departamento.nombre %>
  </div>
  <div class='col-6' align='center'>
    Municipio <%= @municipio.nombre %>
  </div>
</div>

<% @filtro = {
  municipio_id: @municipio.id 
} %>
<%= render partial: 'tabla_resultados' %>


<% Zona.where(municipio_id: @municipio.id).each do |z| %>
  <div class='ressubitem'>
    <%= link_to("Zona #{z.zona}", elecciones_zona_path(zona: z.zona)) %>
  </div>
<% end %>

<div class='ressuperitem'>
  <%= link_to('Departamento de este municipio', elecciones_departamental_path(
    coddep: @departamento.codreg)) %>
</div>

app/views/elecciones/nacional.html.erb
<div class='row'>
  <div class='col-12' align='center'>
    Totales tabulados a nivel nacional para <%= @eleccion.nombre %>
  </div>
</div>

<% @filtro = {
} %>
<%= render partial: 'tabla_resultados' %>

<% Sip::Departamento.habilitados.where(id_pais: 170).each do |d| %>
  <div class='ressubitem'>
    <% puts "OJO #{d.nombre}" %>
    <%= link_to("Departamento #{d.nombre}", 
                elecciones_departamental_path(coddep: d.codreg)) %>
  </div>
<% end %>

app/views/elecciones/puesto.html.erb
<div class='row'>
  <div class='col-12' align='center'>
    Totales tabulados por puesto para <%= @eleccion.nombre %>
  </div>
</div>
<div class='row'>
  <div class='col-6' align='center'>
    Departamento: <%= @departamento.nombre %>
  </div>
  <div class='col-6' align='center'>
    Municipio <%= @municipio.nombre %>
  </div>
</div>
<div class='row'>
  <div class='col-4' align='center'>
    Zona <%= @zona.zona %>
  </div>
  <div class='col-4' align='center'>
    Puesto <%= @puesto.puesto %>
  </div>
</div>

<% @filtro = {
  puesto: @puesto.id,
  zona: @zona.id,
  municipio_id: @municipio.id 
} %>

<%= render partial: 'tabla_resultados' %>

<% Mesa.where(puesto_id: @puesto.id).each do |m| %>
  <div class='ressubitem'>
    <%= link_to("Mesa #{m.mesa}", elecciones_mesa_path(mesa: m.mesa)) %>
  </div>
<% end %>


<div class='ressuperitem'>
  <%= link_to('Zona de este puesto', elecciones_zona_path(zona: @zona.zona)) %>
</div>

app/views/elecciones/zona.html.erb
<div class='row'>
  <div class='col-12' align='center'>
    Totales tabulados por zona para <%= @eleccion.nombre %>
  </div>
</div>
<div class='row'>
  <div class='col-6' align='center'>
    Departamento: <%= @departamento.nombre %>
  </div>
  <div class='col-6' align='center'>
    Municipio <%= @municipio.nombre %>
  </div>
</div>
<div class='row'>
  <div class='col-4' align='center'>
    Zona <%= @zona.zona %>
  </div>
</div>

<% @filtro = {
  zona: @zona.id,
  municipio_id: @municipio.id 
} %>
<%= render partial: 'tabla_resultados' %>


<% Puesto.where(zona_id: @zona.id).each do |p| %>
  <div class='ressubitem'>
    <%= link_to("Puesto #{p.puesto} (#{p.nompuesto})", elecciones_puesto_path(puesto: p.puesto)) %>
  </div>
<% end %>

<div class='ressuperitem'>
  <%= link_to('Municipio de esta zona', elecciones_municipal_path(munid: @municipio.codreg)) %>
</div>